version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck

  exclusions:
    paths:
      - go-sdk
      - src/swan
      - src/tool
      - src/wmcp
    rules:
      - path: _test\.go
        linters:
          - errcheck
